install.packages("devtools", repos = "http://cran.us.r-project.org")
install.packages("rlang", repos = "http://cran.us.r-project.org")
devtools::install_github("IDEMSInternational/cdms.products", ref = "2d4babe")
devtools::install_github("IDEMSInternational/epicsawrap", ref = "dde8d98")
devtools::install_github("IDEMSInternational/epicsadata", ref = "db742f9")
q()